name: td
description: A new Flutter project.
homepage: https://github.com/Sproute777/td
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 4.9.0
  freezed_annotation: 2.4.1
  flame_bloc: ^1.10.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  flame: ">=1.15.0"
  dev_assets:
    path: packages/dev_assets
  astar_dart:
    path: packages/astar_dart
  bloc_concurrency: ^0.2.5
  injectable: ^2.4.2
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  go_router_builder:
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2

  #  flutter pub run intl_utils:generate
  intl_utils: ^2.8.5
  flutter_lints: ^3.0.1
  theme_tailor: 3.0.1
  flutter_gen_runner: ^5.3.1
  retrofit_generator: ^8.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/weapon/
    - assets/images/enemy/
    - assets/images/neutual/
    - assets/images/
    - assets/weaponParams.json
    - assets/weaponParams.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
